version: "3"
services:

  mauticdb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mauticDev123!
    ports:
      - "6379"
    networks:
      - frontend
    deploy:
      restart_policy:
        condition: on-failure

  mautic:
    image: autoize/mautic:latest
    links:
      - mauticdb:mysql
    ports:
      - 8080:80
    networks:
      - frontend
    depends_on:
      - mauticdb
    deploy:
      restart_policy:
        condition: on-failure

  # worker:
  #   image: dockersamples/examplevotingapp_worker
  #   networks:
  #     - frontend
  #     - backend
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     labels: [APP=VOTING]
  #     restart_policy:
  #       condition: on-failure
  #       delay: 10s
  #       max_attempts: 3
  #       window: 120s
  #     placement:
  #       constraints: [node.role == manager]

networks:
  frontend:
  # backend:

volumes:
  db-data: